/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SesionProblemasDos;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public boolean someLibraryMethodTwo() {
        return false;
    }
}
